/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== MagicUI.xml ==================
static const unsigned char temp_binary_data_1[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\">\r\n"
"          <media/>\r\n"
"        </plot-view>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"0\" resize-corner=\"0\" flex-direction=\"column\"\r\n"
"        width=\"1000\" height=\"600\" margin=\"0\" padding=\"\">\r\n"
"    <View flex-grow=\"1.0\">\r\n"
"      <View caption=\"DCO\" border=\"1\">\r\n"
"        <View flex-direction=\"column\" margin=\"0\" padding=\"0\" flex-grow=\"1.75\">\r\n"
"          <View flex-direction=\"column\" caption=\"Range\">\r\n"
"            <ComboBox parameter=\"DCORange\" max-height=\"50\"/>\r\n"
"          </View>\r\n"
"          <View flex-direction=\"column\" caption=\"LFO trigger\">\r\n"
"            <ComboBox parameter=\"LFOTrigMode\" max-height=\"50\" min-height=\"\"/>\r\n"
"          </View>\r\n"
"          <View caption=\"PWM mod\">\r\n"
"            <ComboBox parameter=\"DCOPWMMod\" max-height=\"50\"/>\r\n"
"          </View>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"LFO\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"DCOPitchModDepth\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"PWM\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"DCOPWMDepth\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Pulse\">\r\n"
"          <Slider slider-textbox=\"no-textbox\" parameter=\"DCOPulseLevel\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Saw\">\r\n"
"          <Slider slider-textbox=\"no-textbox\" parameter=\"DCOSawLevel\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Sub\">\r\n"
"          <Slider slider-textbox=\"no-textbox\" parameter=\"DCOSubLevel\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Noise\">\r\n"
"          <Slider slider-textbox=\"no-textbox\" parameter=\"DCONoiseLevel\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View flex-direction=\"column\" caption=\"HPF\" border=\"1\" flex-grow=\"0.2\"\r\n"
"            flex-shrink=\"1.0\">\r\n"
"        <View caption=\"Freq\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"HPF\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"VCF\" border=\"1\" flex-shrink=\"1.0\" flex-grow=\"0.8\">\r\n"
"        <View caption=\"Freq\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFCutoff\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Res\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFResonance\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Env\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFEnv\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"LFO\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFLFO\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Kybd\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFKey\"/>\r\n"
"        </View>\r\n"
"        <View caption=\"Bend\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" parameter=\"VCFBendDepth\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View flex-grow=\"0.8\" border=\"\">\r\n"
"      <View caption=\"LFO\" border=\"1\" flex-grow=\"0.5\">\r\n"
"        <View flex-direction=\"column\" caption=\"Rate\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"LFORate\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"Delay\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"LFODelay\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"VCA\" border=\"1\" flex-grow=\"0.6\">\r\n"
"        <View flex-direction=\"column\" caption=\"Type\">\r\n"
"          <ComboBox parameter=\"VCAType\" max-height=\"50\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"Depth\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"VCADepth\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"Env\" border=\"1\" flex-grow=\"0.6\">\r\n"
"        <View flex-direction=\"column\" caption=\"A\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"ENVAttack\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"D\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"ENVDecay\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"S\" flex-grow=\"1.0\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"ENVSustain\"/>\r\n"
"        </View>\r\n"
"        <View flex-direction=\"column\" caption=\"R\">\r\n"
"          <Slider slider-type=\"linear-vertical\" slider-textbox=\"no-textbox\" flex-grow=\"1.0\"\r\n"
"                  flex-align-self=\"\" parameter=\"ENVRelease\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"Chorus\" border=\"1\" flex-grow=\"0.5\">\r\n"
"        <ToggleButton text=\"I\" parameter=\"ChorusI\"/>\r\n"
"        <ToggleButton text=\"II\" parameter=\"ChorusII\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View flex-grow=\"0.2\" border=\"1\">\r\n"
"      <Label flex-grow=\"0.1\" text=\"This version is alpha quality. There are no compatibility guarantees.\"\r\n"
"             font-size=\"14\" label-text=\"FFFF8D8D\"/>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n"
"\0";

const char* MagicUI_xml = (const char*) temp_binary_data_1;
}
