name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_arm:
    runs-on: ubuntu-20.04
    container: stonepreston/juce-arm-linux-cross-compiler:latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # -DPACKAGE_TESTS=OFF so that the tests dont get executed once build is finished
      - name: build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPACKAGE_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build -j8
          zip -r -j LMN-3-arm-linux-gnueabihf.zip ./build/LMN-3_artefacts/Release/LMN-3 ./LICENSE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LMN-3-arm-linux-gnueabihf
          path: LMN-3-arm-linux-gnueabihf.zip
          retention-days: 1

  build_aarch64:
    runs-on: ubuntu-20.04
    container: stonepreston/juce-aarch64-linux-cross-compiler:latest

    needs: build_arm

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # -DPACKAGE_TESTS=OFF so that the tests dont get executed once build is finished
      - name: build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPACKAGE_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build -j8
          zip -r -j LMN-3-aarch64-linux-gnu.zip ./build/LMN-3_artefacts/Release/LMN-3 ./LICENSE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LMN-3-aarch64-linux-gnu
          path: LMN-3-aarch64-linux-gnu.zip
          retention-days: 1